apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: user-test
spec:
  type: ClusterIP
  selector:
    app: user-learning
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 8081