spring:
  application.name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: post
          uri: http://localhost:8082
          predicates:
            - Path=/posts/**




server:
  port: 80

#debug: true