spring:
  application.name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: user
            uri: http://user.test:8081
            predicates:
              - Path=/users/**
          - id: post
            uri: http://post.test:8082
            predicates:
              - Path=/posts/**




server:
  port: 80

#debug: true