apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: gateway-learning
  ports:
    - name: http
      port: 80
      targetPort: 80
