apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: app-learning
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 9090