apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test-app
spec:
  replicas: 10
  minReadySeconds: 30 # wait for 30 sec before pod is ready going to next
  strategy:
    type: RollingUpdate
    maxUnavailable: 1
    maxSurge: 2
  selector:
    matchLabels:
      app: app-learning
  template:
    metadata:
      labels:
        name: app
        app: app-learning
    spec:
      containers:
        - name: app
          image: varunkumar12aug/app:v3.3
          imagePullPolicy: Always
          ports:
            - containerPort: 9090