apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test-app
spec:
  replicas: 5
  minReadySeconds: 30 # wait for 30 sec before pod is ready going to next
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: app-learning
  template:
    metadata:
      labels:
        name: app
        app: app-learning
    spec:
      containers:
        - name: app
          image: varunkumar12aug/app:v2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /app       # endpoint to check
              port: 80
            initialDelaySeconds: 10   # wait before first check
            periodSeconds: 10         # check every 10s
            failureThreshold: 3       # restart after 3 failures
          readinessProbe:
            httpGet:
              path: /app       # endpoint to check readiness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3