apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: test-app
spec:
  type: NodePort
  selector:
    app: app-learning
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001